version: '3'

services:
  db:
    volumes: 
      - mariadb-data:/var/lib/mysql
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    image: "${MARIADB_CONTAINER_NAME}"
    container_name: "${MARIADB_CONTAINER_NAME}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - shiporders_network

  api:
    volumes: 
      - ./api:/var/www/html
    image: "${API_CONTAINER_NAME}"
    container_name: "${API_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        TIMEZONE: "${TIMEZONE}"
        DBPASS: "${DB_ROOT_PASSWD}"
        DBUSER: "${DB_USER}"
        DBNAME: "${DB_NAME}"
        APITOKEN: "${API_TOKEN}"
    depends_on:
      - "db"
    networks:
      - shiporders_network

  webserver:
    volumes: 
      - ./api:/var/www/html
    image: "${NGINX_CONTAINER_NAME}"
    container_name: "${NGINX_CONTAINER_NAME}"
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${API_HTTP_PORT}:80"
      - "${API_HTTPS_PORT}:443"
    depends_on:
      - "api"
    networks:
      - shiporders_network

  frontend:
    volumes:
      - ./frontend:/app
    image: "${FRONTEND_CONTAINER_NAME}"
    container_name: "${FRONTEND_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        API_PORT: "${API_HTTP_PORT}"
    ports:
      - "${FRONTEND_HTTP_PORT}:8080"
      - "${FRONTEND_HTTPS_PORT}:4533"
    depends_on:
      - "webserver"
    networks:
      - shiporders_network

networks:
  shiporders_network:
    driver: bridge

volumes:
  mariadb-data: