version: '3'

services:
  api:
    volumes: 
      - ./api:/var/www/html
    image: "${API_CONTAINER_NAME}"
    container_name: "${API_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        TIMEZONE: "${TIMEZONE}"
    depends_on:
      - "db"
    networks:
      - shiporders_network

  api-server:
    volumes: 
      - ./api:/var/www/html
    image: "${NGINX_API_CONTAINER_NAME}"
    container_name: "${NGINX_API_CONTAINER_NAME}"
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${API_HTTP_PORT}:80"
      - "${API_HTTPS_PORT}:443"
    depends_on:
      - "api"
    networks:
      - shiporders_network

  composer:
    volumes:
      - ./api:/app
    image: "${COMPOSER_CONTAINER_NAME}"
    container_name: "${COMPOSER_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - "api"
    networks:
      - shiporders_network

  bash:
    volumes:
      - ./api:/app
    image: "${BASH_CONTAINER_NAME}"
    container_name: "${BASH_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/bash/Dockerfile
    networks:
      - shiporders_network

  frontend:
    volumes:
      - ./frontend:/app
    image: "${FRONTEND_CONTAINER_NAME}"
    container_name: "${FRONTEND_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "${FRONTEND_PORT}:8080"
    depends_on:
      - "api"
    networks:
      - shiporders_network
  db:
    volumes: 
      - mariadb-data:/var/lib/mysql
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    image: "${MARIADB_CONTAINER_NAME}"
    container_name: "${MARIADB_CONTAINER_NAME}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - shiporders_network

networks:
  shiporders_network:
    driver: bridge

volumes:
  mariadb-data: