version: '3'

services:
  bash:
    volumes:
      - ./api:/app
    image: "shiporders_bash"
    container_name: "shiporders_bash"
    build:
      context: .
      dockerfile: ./docker/bash/Dockerfile
    networks:
      - shiporders_network

networks:
  shiporders_network:
    driver: bridge